### ISSUE TITLE
Tastatur verschwindet nicht nach Eingabe

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#107]
Tastatur verschwindet nicht nach Text Eingabe und blockiert so das UI. 
Sollte jemand diesen Fehler bemerken, dann das entsprechende EditText feld um folgendes Attribut erweitern.
``` XML
android:imeOptions="actionDone"
```

**Comment by Leosssss** [comment]
Tastutur geht schon weg, wenn man nach der Eingabe "Line Feed" klickt
