### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Leosssss** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#117]
Button works also without items checked

**Comment by TobiasZels** [comment]
Wann tritt der Fehler auf? Auf dem Dev funktioniert bei mir der Button erst wenn alles ausgewählt wurde.

**Comment by Leosssss** [comment]
Die alte Version, die ich gestern gehabt, funktioniert es nicht... dann schaue ichs später bei aktuellen Codes nach.

**Comment by Leosssss** [comment]
ES FUNKTIONIERT TATSÄCHLICH!! ^^
