### ISSUE TITLE
Merge hat MeetingHistory Adapter Klasse zerstört

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#122]
~~Merge hat die Änderungen an der MeetingHistory Adapter Klasse verworfen~~
Noch alte referenz an "Mettingdatabase"

**Comment by Leosssss** [comment]
!!! es tut mir Leid !!

**Comment by TobiasZels** [comment]
Nicht deine schuld, habe die Datenbank ausgetauscht, sodass dein delete ins leere lief hab es in #123 behoben.
