### ISSUE TITLE
Startseite/BottomNavigation ergänzen

### ISSUE THREAD

**Issue by jmhoffmann9612** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#161]
Vier Unterseiten in BottomNavigation

- [ ] Startseite (erst Mal grobe Erklärung)
- [x] Verlauf
- [ ] Teilnehmerverwaltung
- [x] Presetverwaltung

**Comment by MaximilianHuber** [comment]
vlt @90 anmerken mit rki daten für Startseite
