### ISSUE TITLE
Teilnehmer in Meetingsverlauf anzeigen

### ISSUE THREAD

**Issue by jmhoffmann9612** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#163]

**Comment by jmhoffmann9612** [comment]
![Bild](https://user-images.githubusercontent.com/46888078/159548471-f669e891-9a0e-4b63-a60c-5c57037db398.png)

Bin so mittel-zufrieden mit der Implementation, weil Chips normalerweise klickbar sind und das evtl. in der Bewertung hinterher wegen verwirrender Usability Abzüge gibt (vgl. Checkliste mit Radiobuttons). Wollte aber nicht auch einfach nur Plaintext oder einen Dialog hernehmen, aber eine Liste für aufzuziehen erscheint mir exzessiv.

Falls jemand noch eine bessere Idee oder Vorlage hat, gib Bescheid, ich würde das dann noch implementieren

**Comment by TobiasZels** [comment]
Wollten wir nicht Email und Impfstatus anzeigen, kann sich ja ein weiteres Fenster mit diesen Informationen öffnen wenn man auf die Namen klickt.

**Comment by jmhoffmann9612** [comment]
Ups, hatten wir das so gesagt? Muss ich verschwitzt haben... Weil das gäbe den Chips was klickbares.

Extra Fenster oder reicht einfach ein [Alert dialog](https://material.io/components/dialogs#alert-dialog) mit ner Custom View? Ich kann das ja immerhin so bauen, dass sich bei Klick auf die Mailadresse dann die Email-App öffnet oder so.

**Comment by TobiasZels** [comment]
Alert dialog reicht erstmal, solange die Funktionen vorhanden sind können wir das Design ja jederzeit noch anpassen.

**Comment by jmhoffmann9612** [comment]
![image](https://user-images.githubusercontent.com/46888078/159970567-823741ad-016c-4fb3-b31f-f43671aec1c9.png)

Nutzt momentan noch Platzhalter für die Mailadresse. Ist mit TODO im Quellcode aber entsprechend markiert
