### ISSUE TITLE
App crashes when click the "+" button the first time open the application after installation

### ISSUE THREAD

**Issue by Leosssss** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#168]

**Comment by TobiasZels** [comment]
Ja, habe die Funktion das Standard Preset zu erstellen im Settings Fragment geschrieben. Die muss logischerweise in der Main Activity aufgerufen werden, sodass sie beim ersten Start das Preset erstellt, ansonsten läuft die Funktion natürlich ins leere. Kann ich morgen beheben.
