### ISSUE TITLE
Farbgebung

### ISSUE THREAD

**Issue by jmhoffmann9612** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#44]
### Beschreibung

- Hintergrund: Systemeinstellung
- Hell: Schwarzer Text auf weißem Hintergrund (#f4f3f8 - dunkleres weiß)
- Dunkel: Weißer Text auf schwarzem Hintergrund

Ansonsten: Blauer Hintergrund, weißer Text (z.B. für Buttons) (#004dba - Blau)

**Comment by Leosssss** [comment]
Theme: Hell: https://material.io/resources/color/#!/?view.left=0&view.right=1&primary.color=004DBA

**Comment by Leosssss** [comment]
https://paletton.com/#uid=13E0u0k++BGy2ZHZx+V+WrI+glx

**Comment by jmhoffmann9612** [comment]
https://github.com/ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent/releases/tag/v0.10.2
