### ISSUE TITLE
Speicherung der Meeting Daten in der Datenbank 

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#54]
Speichern von Daten nach jedem Meeting.
Daten welche gespeichert werden sollen:
- [x] Start Zeit
- [x] End Zeit
- [x] Dauer
- [x] Teilnehmer
- [x] Ort
- [ ] Intervalle

**Comment by jmhoffmann9612** [comment]
https://github.com/ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent/releases/tag/v0.10.2

**Comment by TobiasZels** [comment]
Alte Datenbank durch ROOM ersetzt.
