### ISSUE TITLE
Implementieren von Onboarding-Maßnahmen

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#66]
- [ ] Implementieren von Onboarding-Maßnahmen

**Comment by jmhoffmann9612** [comment]
Ich werde mich weitgehend hieran orientieren: https://material.io/design/communication/onboarding.html#top-user-benefits-model

Ich gucke erst mal, dass ich dieses Auto-rotating carousel zum Laufen bekomme und dass dieses nur öffnet, wenn die App das erste Mal gestartet wird. Wie wir das Ganze dann füllen, sollten wir nochmal was Gruppe diskutieren.

- [ ] Öffne eine Onboarding-Activity, wenn App das erste Mal gestartet wird
- [ ] Die Onboarding-Activity enthält drei Seiten, zunächst mit Platzhaltern, sowie einen "Get Started"-Button, welcher die Activity schließt
- [ ] Das `Carousel` rotiert alle zwei bis drei Sekunden automatisch.
- [ ] Das Auto-Rotieren schaltet aus, wenn der Nutzer selbst mit dem `Carousel` interagiert.
