### ISSUE TITLE
Implementieren einer Bottom Navigation

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#67]
- [x] Verlinkung von Verlauf (links)
- [x] Verlinkung von Einstellungen/Presets (rechts)
- [x] Meetingstart (mitte)
Vergleiche Corona App:
![Navbar](https://user-images.githubusercontent.com/25437804/158147597-1df55742-fece-4966-981e-6a01d4ef6d66.PNG)

**Comment by TobiasZels** [comment]
Aktuelle Leiste ist "Corona-Blau", vielleicht die Leiste dunkel Grau und blau nur als Akzent Farbe verwenden? 
@jmhoffmann9612 
@MaximilianHuber 
@Leosssss

**Comment by jmhoffmann9612** [comment]
Gute Idee, glaub ich. Wobei Farben zur Not keine Riesentortur um ändern sind.
