### ISSUE TITLE
Implementieren von Custom Timer

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#68]
- [x] Custom Timer erstellbar in den Einstellungen/Presets
- [x] Anzeigen ausgewählter Timer im Meeting Dashboard unter Timer

**Comment by TobiasZels** [comment]
Habe zur Darstellung von Countdowns zwei Objekte erstellt. 

Das AdvancedCountdownObject beinhaltet den Namen sowie den Status (an/aus) des Countdowns.
Jedes AdvancedCountdownObject besitzt ein oder mehrere AdvancedCountdownItem Objecte, welche in einer ArrayList gespeichert werden. 
Jedes AdvancedCountdownItem besitzt einen Long subCountdown welcher die maximale Dauer des Countdowns anzeigt und eine Beschreibung.

Im nachfolgenden der Code der beiden Objekte, wäre gut wenn du die Custom Timer in diesem Format speichern könntest.

``` Java
    public static class AdvancedCountdownObject{
        String mCountdownName;
        Boolean mEnabled;

        ArrayList<RecyclerViewAdvancedCountdownItemAdapter.AdvancedCountdownItem> mItems;

        public AdvancedCountdownObject(String mCountdownName,
                                       Boolean mEnabled,
                                       ArrayList<RecyclerViewAdvancedCountdownItemAdapter.AdvancedCountdownItem> mItems) {
            this.mCountdownName = mCountdownName;
            this.mEnabled = mEnabled;
            this.mItems = mItems;
        }
    }
```

```Java
 public static class AdvancedCountdownItem{
        Long subCountdown;
        String subCountdownDescription;

        public AdvancedCountdownItem(Long subCountdown,
                                       String onSubCountdownDescription) {
            this.subCountdown = subCountdown;
            this.subCountdownDescription = onSubCountdownDescription;
        }
    }
```

**Comment by MaximilianHuber** [comment]
Momentan noch nicht custom benennbar
