### ISSUE TITLE
Überarbeitung der Designs für kleine Bildschirme

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#78]
Überarbeitung der Activities für kleine Geräte.

**Comment by Leosssss** [comment]
For responsive layout
1. use constraintlayout
2. avoid z.B. giving a view width of 200dp

**Comment by TobiasZels** [comment]
Linear Layout funktioniert auch für responsive Designs, da diese mit "wrap_content" automatisch dem Inhalt anpassen und unter bzw. nebeneinander gestapelt werden.

**Comment by Leosssss** [comment]
ahh ok, hatte es im einen Video Tutorial gesehen
