### ISSUE TITLE
Anzeigen der RKI Daten

### ISSUE THREAD

**Issue by TobiasZels** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#90]
Verwendung einer API um die RKI Daten (Neuinfektionen, Hospitalisierung, …) auf der Startseite anzuzeigen.
API: https://api.corona-zahlen.org/
GET: https://api.corona-zahlen.org/germany

**Comment by jmhoffmann9612** [comment]
Meiner Meinung nach: ist nice-to-have, aber nicht die eigentliche Aufgabe unserer App. Müssten halt auch Dinge beachten, wie die Anzeige aussieht, wenn kein Internet da ist, etc.
