### ISSUE TITLE
Optionen bei Alerts teilweise nicht sichtbar

### ISSUE THREAD

**Issue by jmhoffmann9612** [ASE-Projekte-WS-2021/ase-ws-21-konferenzassistent#95]
Lassen sich aber weiterhin betätigen und der Platz, wo die Buttons normalerweise wären, ist auch da. Vermutlich weißer Text auf weißem Hintergrund?

**Comment by TobiasZels** [comment]
Hast du den aktuellen Dev stand, dachte ich hätte das mit 79e16e7dfd09a894e2cb4c057ab726858376112c gelöst. Falls du neue Alerts erstellt hast musst du ihnen im Builder einen Style zuweisen.

```java
AlertDialog.Builder builder = new AlertDialog.Builder(this, R.style.dialogAlertStyle);
```
Damit sollten Buttons wieder angezeigt werden

**Comment by jmhoffmann9612** [comment]
Ah, wusste ich nicht. Haben aber auch noch ein paar andere AlertDialoge im dev gefehlt. Hab hoffentlich jetzt alle erwischt. 93c47a8f3942b3d212189546d86dd86ec91decc9
